// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePanelDb;

#nullable disable

namespace SecurePanelDb.Migrations
{
    [DbContext(typeof(SecurePanelDbContext))]
    [Migration("20260204184706_V1_0_0_0")]
    partial class V1_0_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SecurePanelDb.Models.AlarmChannel", b =>
                {
                    b.Property<int>("AlarmChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Identifier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Online")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmChannelId");

                    b.ToTable("AlarmChannels");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchedule", b =>
                {
                    b.Property<int>("AlarmScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeopleEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PetsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VehicleEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmScheduleId");

                    b.ToTable("AlarmSchedules");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmScheme", b =>
                {
                    b.Property<int>("AlarmSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlarmScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmSchemeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmSchemeId");

                    b.HasIndex("AlarmChannelId");

                    b.HasIndex("AlarmScheduleId")
                        .IsUnique();

                    b.HasIndex("AlarmSchemeTypeId");

                    b.ToTable("AlarmSchemes");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemeType", b =>
                {
                    b.Property<int>("AlarmSchemeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AlarmSchemeTypeId");

                    b.ToTable("AlarmSchemeTypes");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmUser", b =>
                {
                    b.Property<int>("AlarmUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlarmCodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlarmUserId");

                    b.ToTable("AlarmUsers");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmScheme", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AlarmChannel", "AlarmChannel")
                        .WithMany("AlarmSchemes")
                        .HasForeignKey("AlarmChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePanelDb.Models.AlarmSchedule", "AlarmSchedule")
                        .WithOne("AlarmScheme")
                        .HasForeignKey("SecurePanelDb.Models.AlarmScheme", "AlarmScheduleId");

                    b.HasOne("SecurePanelDb.Models.AlarmSchemeType", "AlarmSchemeType")
                        .WithMany()
                        .HasForeignKey("AlarmSchemeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmChannel");

                    b.Navigation("AlarmSchedule");

                    b.Navigation("AlarmSchemeType");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmChannel", b =>
                {
                    b.Navigation("AlarmSchemes");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchedule", b =>
                {
                    b.Navigation("AlarmScheme");
                });
#pragma warning restore 612, 618
        }
    }
}
