// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePanelDb;

#nullable disable

namespace SecurePanelDb.Migrations
{
    [DbContext(typeof(SecurePanelDbContext))]
    [Migration("20260202132419_V1_0_0_0")]
    partial class V1_0_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SecurePanelDb.Models.AiSchedule", b =>
                {
                    b.Property<int>("AiScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiDogCat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiOther")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiPeople")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiVehicle")
                        .HasColumnType("INTEGER");

                    b.HasKey("AiScheduleId");

                    b.ToTable("AiSchedules");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmScheme", b =>
                {
                    b.Property<int>("AlarmSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlarmSchemeTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmSchemeId");

                    b.HasIndex("AlarmSchemeTypeId");

                    b.ToTable("AlarmSchemes");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemeAudio", b =>
                {
                    b.Property<int>("AlarmSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmSchemeId", "AudioId");

                    b.HasIndex("AudioId");

                    b.ToTable("AlarmSchemeAudios");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemeBuzzer", b =>
                {
                    b.Property<int>("AlarmSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuzzerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmSchemeId", "BuzzerId");

                    b.HasIndex("BuzzerId");

                    b.ToTable("AlarmSchemeBuzzers");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemePush", b =>
                {
                    b.Property<int>("AlarmSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PushId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmSchemeId", "PushId");

                    b.HasIndex("PushId");

                    b.ToTable("AlarmSchemePushes");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemeType", b =>
                {
                    b.Property<int>("AlarmSchemeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlarmSchemeTypeId");

                    b.ToTable("AlarmSchemeTypes");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmUser", b =>
                {
                    b.Property<int>("AlarmUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlarmCodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlarmUserId");

                    b.ToTable("AlarmUsers");
                });

            modelBuilder.Entity("SecurePanelDb.Models.Audio", b =>
                {
                    b.Property<int>("AudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AiScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("AudioId");

                    b.HasIndex("AiScheduleId");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("SecurePanelDb.Models.Buzzer", b =>
                {
                    b.Property<int>("BuzzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AiScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DiskErrorAlert")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DiskFullAlert")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IpConfigAlert")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NvrDisconnectAlert")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuzzerId");

                    b.HasIndex("AiScheduleId");

                    b.ToTable("Buzzers");
                });

            modelBuilder.Entity("SecurePanelDb.Models.Push", b =>
                {
                    b.Property<int>("PushId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AiScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScheduleEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("PushId");

                    b.HasIndex("AiScheduleId");

                    b.ToTable("Push");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmScheme", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AlarmScheme", "AlarmSchemeType")
                        .WithMany()
                        .HasForeignKey("AlarmSchemeTypeId");

                    b.Navigation("AlarmSchemeType");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemeAudio", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AlarmScheme", "AlarmScheme")
                        .WithMany()
                        .HasForeignKey("AlarmSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePanelDb.Models.Audio", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmScheme");

                    b.Navigation("Audio");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemeBuzzer", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AlarmScheme", "AlarmScheme")
                        .WithMany()
                        .HasForeignKey("AlarmSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePanelDb.Models.Buzzer", "Buzzer")
                        .WithMany()
                        .HasForeignKey("BuzzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmScheme");

                    b.Navigation("Buzzer");
                });

            modelBuilder.Entity("SecurePanelDb.Models.AlarmSchemePush", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AlarmScheme", "AlarmScheme")
                        .WithMany()
                        .HasForeignKey("AlarmSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePanelDb.Models.Push", "Push")
                        .WithMany()
                        .HasForeignKey("PushId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmScheme");

                    b.Navigation("Push");
                });

            modelBuilder.Entity("SecurePanelDb.Models.Audio", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AiSchedule", "AiSchedule")
                        .WithMany()
                        .HasForeignKey("AiScheduleId");

                    b.Navigation("AiSchedule");
                });

            modelBuilder.Entity("SecurePanelDb.Models.Buzzer", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AiSchedule", "AiSchedule")
                        .WithMany()
                        .HasForeignKey("AiScheduleId");

                    b.Navigation("AiSchedule");
                });

            modelBuilder.Entity("SecurePanelDb.Models.Push", b =>
                {
                    b.HasOne("SecurePanelDb.Models.AiSchedule", "AiSchedule")
                        .WithMany()
                        .HasForeignKey("AiScheduleId");

                    b.Navigation("AiSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
