services:
  secure-panel-api:
    image: ghcr.io/mitchell-josh/esp32reolinksecurepanel:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/SecurePanel.db
      - Logging__LogLevel__ReolinkAPI=Debug
      - Logging__LogLevel__SecurePanelAPI=Debug
      - Settings__Username=${REOLINK_USERNAME}
      - Settings__Password=${REOLINK_PASSWORD}
      - Settings__ReolinkURL=${REOLINK_URL}
    volumes:
      - ./data:/app/data
        
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup