// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#ifndef _REOALARMUI_UI_H
#define _REOALARMUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_PinEntry.h"
#include "screens/ui_SettingsLanding.h"
#include "screens/ui_CameraSelect.h"
#include "screens/ui_CameraSettings.h"
#include "screens/ui_Error.h"
#include "screens/ui_Loading.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
