// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#include "../ui.h"

lv_obj_t * ui_CameraSettings = NULL;
lv_obj_t * ui_LblEnabled = NULL;
lv_obj_t * ui_DropdownEnabled = NULL;
lv_obj_t * ui_LblPeople = NULL;
lv_obj_t * ui_DropdownPeopleEnabled = NULL;
lv_obj_t * ui_LblCarsEnabled = NULL;
lv_obj_t * ui_DropdownCarsEnabled = NULL;
lv_obj_t * ui_LblPets = NULL;
lv_obj_t * ui_DropdownPetsEnabled = NULL;
lv_obj_t * ui_LblOther = NULL;
lv_obj_t * ui_DropdownOtherEnabled = NULL;
lv_obj_t * ui_BtnSettingsOkCS = NULL;
lv_obj_t * ui_LblSettingsOk2 = NULL;
lv_obj_t * ui_BtnSettingsCancelCS = NULL;
lv_obj_t * ui_LblSettingsCancel2 = NULL;
lv_obj_t * ui_BtnUseCurrentSettings = NULL;
lv_obj_t * ui_LblUserCurrentSettings = NULL;
lv_obj_t * ui_LblCameraName = NULL;
// event funtions

// build funtions

void ui_CameraSettings_screen_init(void)
{
    ui_CameraSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CameraSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CameraSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CameraSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblEnabled = lv_label_create(ui_CameraSettings);
    lv_obj_set_width(ui_LblEnabled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblEnabled, 0);
    lv_obj_set_y(ui_LblEnabled, -81);
    lv_obj_set_align(ui_LblEnabled, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblEnabled, "Enabled:");
    lv_obj_set_style_text_color(ui_LblEnabled, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblEnabled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownEnabled = lv_dropdown_create(ui_CameraSettings);
    lv_dropdown_set_options(ui_DropdownEnabled, "Enabled\nDisabled");
    lv_obj_set_width(ui_DropdownEnabled, 314);
    lv_obj_set_height(ui_DropdownEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownEnabled, 0);
    lv_obj_set_y(ui_DropdownEnabled, -57);
    lv_obj_set_align(ui_DropdownEnabled, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownEnabled, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LblPeople = lv_label_create(ui_CameraSettings);
    lv_obj_set_width(ui_LblPeople, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPeople, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeople, -80);
    lv_obj_set_y(ui_LblPeople, -29);
    lv_obj_set_align(ui_LblPeople, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeople, "People:");
    lv_obj_set_style_text_color(ui_LblPeople, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeople, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownPeopleEnabled = lv_dropdown_create(ui_CameraSettings);
    lv_dropdown_set_options(ui_DropdownPeopleEnabled, "Enabled\nDisabled");
    lv_obj_set_width(ui_DropdownPeopleEnabled, 155);
    lv_obj_set_height(ui_DropdownPeopleEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownPeopleEnabled, -80);
    lv_obj_set_y(ui_DropdownPeopleEnabled, -2);
    lv_obj_set_align(ui_DropdownPeopleEnabled, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownPeopleEnabled, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LblCarsEnabled = lv_label_create(ui_CameraSettings);
    lv_obj_set_width(ui_LblCarsEnabled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCarsEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblCarsEnabled, 79);
    lv_obj_set_y(ui_LblCarsEnabled, -28);
    lv_obj_set_align(ui_LblCarsEnabled, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCarsEnabled, "Cars:");
    lv_obj_set_style_text_color(ui_LblCarsEnabled, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCarsEnabled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownCarsEnabled = lv_dropdown_create(ui_CameraSettings);
    lv_dropdown_set_options(ui_DropdownCarsEnabled, "Enabled\nDisabled");
    lv_obj_set_width(ui_DropdownCarsEnabled, 155);
    lv_obj_set_height(ui_DropdownCarsEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownCarsEnabled, 79);
    lv_obj_set_y(ui_DropdownCarsEnabled, -2);
    lv_obj_set_align(ui_DropdownCarsEnabled, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCarsEnabled, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LblPets = lv_label_create(ui_CameraSettings);
    lv_obj_set_width(ui_LblPets, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPets, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPets, -80);
    lv_obj_set_y(ui_LblPets, 24);
    lv_obj_set_align(ui_LblPets, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPets, "Pets:");
    lv_obj_set_style_text_color(ui_LblPets, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPets, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownPetsEnabled = lv_dropdown_create(ui_CameraSettings);
    lv_dropdown_set_options(ui_DropdownPetsEnabled, "Enabled\nDisabled");
    lv_obj_set_width(ui_DropdownPetsEnabled, 155);
    lv_obj_set_height(ui_DropdownPetsEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownPetsEnabled, -80);
    lv_obj_set_y(ui_DropdownPetsEnabled, 48);
    lv_obj_set_align(ui_DropdownPetsEnabled, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownPetsEnabled, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LblOther = lv_label_create(ui_CameraSettings);
    lv_obj_set_width(ui_LblOther, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblOther, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblOther, 79);
    lv_obj_set_y(ui_LblOther, 24);
    lv_obj_set_align(ui_LblOther, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblOther, "Other:");
    lv_obj_set_style_text_color(ui_LblOther, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblOther, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownOtherEnabled = lv_dropdown_create(ui_CameraSettings);
    lv_dropdown_set_options(ui_DropdownOtherEnabled, "Enabled\nDisabled");
    lv_obj_set_width(ui_DropdownOtherEnabled, 155);
    lv_obj_set_height(ui_DropdownOtherEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownOtherEnabled, 79);
    lv_obj_set_y(ui_DropdownOtherEnabled, 48);
    lv_obj_set_align(ui_DropdownOtherEnabled, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownOtherEnabled, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_BtnSettingsOkCS = lv_btn_create(ui_CameraSettings);
    lv_obj_set_width(ui_BtnSettingsOkCS, 75);
    lv_obj_set_height(ui_BtnSettingsOkCS, 40);
    lv_obj_set_x(ui_BtnSettingsOkCS, 119);
    lv_obj_set_y(ui_BtnSettingsOkCS, 96);
    lv_obj_set_align(ui_BtnSettingsOkCS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSettingsOkCS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSettingsOkCS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSettingsOkCS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettingsOkCS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSettingsOk2 = lv_label_create(ui_BtnSettingsOkCS);
    lv_obj_set_width(ui_LblSettingsOk2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSettingsOk2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblSettingsOk2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSettingsOk2, "");
    lv_obj_set_style_text_color(ui_LblSettingsOk2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSettingsOk2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSettingsOk2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSettingsCancelCS = lv_btn_create(ui_CameraSettings);
    lv_obj_set_width(ui_BtnSettingsCancelCS, 75);
    lv_obj_set_height(ui_BtnSettingsCancelCS, 40);
    lv_obj_set_x(ui_BtnSettingsCancelCS, -120);
    lv_obj_set_y(ui_BtnSettingsCancelCS, 96);
    lv_obj_set_align(ui_BtnSettingsCancelCS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSettingsCancelCS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSettingsCancelCS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSettingsCancelCS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettingsCancelCS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSettingsCancel2 = lv_label_create(ui_BtnSettingsCancelCS);
    lv_obj_set_width(ui_LblSettingsCancel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSettingsCancel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblSettingsCancel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSettingsCancel2, "X");
    lv_obj_set_style_text_color(ui_LblSettingsCancel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSettingsCancel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSettingsCancel2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnUseCurrentSettings = lv_btn_create(ui_CameraSettings);
    lv_obj_set_width(ui_BtnUseCurrentSettings, 159);
    lv_obj_set_height(ui_BtnUseCurrentSettings, 40);
    lv_obj_set_x(ui_BtnUseCurrentSettings, 0);
    lv_obj_set_y(ui_BtnUseCurrentSettings, 96);
    lv_obj_set_align(ui_BtnUseCurrentSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnUseCurrentSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnUseCurrentSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnUseCurrentSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnUseCurrentSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblUserCurrentSettings = lv_label_create(ui_BtnUseCurrentSettings);
    lv_obj_set_width(ui_LblUserCurrentSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblUserCurrentSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblUserCurrentSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblUserCurrentSettings, "Use Current Settings");
    lv_obj_set_style_text_color(ui_LblUserCurrentSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblUserCurrentSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblUserCurrentSettings, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCameraName = lv_label_create(ui_CameraSettings);
    lv_obj_set_width(ui_LblCameraName, 310);
    lv_obj_set_height(ui_LblCameraName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblCameraName, 0);
    lv_obj_set_y(ui_LblCameraName, -106);
    lv_obj_set_align(ui_LblCameraName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCameraName, "Camera Name");
    lv_obj_set_style_text_color(ui_LblCameraName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCameraName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_CameraSettings_screen_destroy(void)
{
    if(ui_CameraSettings) lv_obj_del(ui_CameraSettings);

    // NULL screen variables
    ui_CameraSettings = NULL;
    ui_LblEnabled = NULL;
    ui_DropdownEnabled = NULL;
    ui_LblPeople = NULL;
    ui_DropdownPeopleEnabled = NULL;
    ui_LblCarsEnabled = NULL;
    ui_DropdownCarsEnabled = NULL;
    ui_LblPets = NULL;
    ui_DropdownPetsEnabled = NULL;
    ui_LblOther = NULL;
    ui_DropdownOtherEnabled = NULL;
    ui_BtnSettingsOkCS = NULL;
    ui_LblSettingsOk2 = NULL;
    ui_BtnSettingsCancelCS = NULL;
    ui_LblSettingsCancel2 = NULL;
    ui_BtnUseCurrentSettings = NULL;
    ui_LblUserCurrentSettings = NULL;
    ui_LblCameraName = NULL;

}
