// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#ifndef UI_CAMERASELECT_H
#define UI_CAMERASELECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CameraSelect
extern void ui_CameraSelect_screen_init(void);
extern void ui_CameraSelect_screen_destroy(void);
extern lv_obj_t * ui_CameraSelect;
extern lv_obj_t * ui_BtnCamera0;
extern lv_obj_t * ui_LblCamera0;
extern lv_obj_t * ui_BtnCamera1;
extern lv_obj_t * ui_LblCamera1;
extern lv_obj_t * ui_BtnCamera2;
extern lv_obj_t * ui_LblCamera2;
extern lv_obj_t * ui_BtnCamera3;
extern lv_obj_t * ui_LblCamera3;
extern lv_obj_t * ui_BtnCamera4;
extern lv_obj_t * ui_LblCamera4;
extern lv_obj_t * ui_BtnCamera5;
extern lv_obj_t * ui_LblCamera5;
extern lv_obj_t * ui_BtnCamera6;
extern lv_obj_t * ui_LblCamera6;
extern lv_obj_t * ui_BtnCamera7;
extern lv_obj_t * ui_LblCamera7;
extern lv_obj_t * ui_BtnSettingsOkSel;
extern lv_obj_t * ui_LblSettingsOk1;
extern lv_obj_t * ui_BtnSettingsCancelSel;
extern lv_obj_t * ui_LblSettingsCancel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

