// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#ifndef UI_CAMERASETTINGS_H
#define UI_CAMERASETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CameraSettings
extern void ui_CameraSettings_screen_init(void);
extern void ui_CameraSettings_screen_destroy(void);
extern lv_obj_t * ui_CameraSettings;
extern lv_obj_t * ui_LblEnabled;
extern lv_obj_t * ui_DropdownEnabled;
extern lv_obj_t * ui_LblPeople;
extern lv_obj_t * ui_DropdownPeopleEnabled;
extern lv_obj_t * ui_LblCarsEnabled;
extern lv_obj_t * ui_DropdownCarsEnabled;
extern lv_obj_t * ui_LblPets;
extern lv_obj_t * ui_DropdownPetsEnabled;
extern lv_obj_t * ui_LblOther;
extern lv_obj_t * ui_DropdownOtherEnabled;
extern lv_obj_t * ui_BtnSettingsOkCS;
extern lv_obj_t * ui_LblSettingsOk2;
extern lv_obj_t * ui_BtnSettingsCancelCS;
extern lv_obj_t * ui_LblSettingsCancel2;
extern lv_obj_t * ui_LblCameraName;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

