// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#include "../ui.h"

lv_obj_t * ui_CameraSelect = NULL;
lv_obj_t * ui_BtnCamera0 = NULL;
lv_obj_t * ui_LblCamera0 = NULL;
lv_obj_t * ui_BtnCamera1 = NULL;
lv_obj_t * ui_LblCamera1 = NULL;
lv_obj_t * ui_BtnCamera2 = NULL;
lv_obj_t * ui_LblCamera2 = NULL;
lv_obj_t * ui_BtnCamera3 = NULL;
lv_obj_t * ui_LblCamera3 = NULL;
lv_obj_t * ui_BtnCamera4 = NULL;
lv_obj_t * ui_LblCamera4 = NULL;
lv_obj_t * ui_BtnCamera5 = NULL;
lv_obj_t * ui_LblCamera5 = NULL;
lv_obj_t * ui_BtnCamera6 = NULL;
lv_obj_t * ui_LblCamera6 = NULL;
lv_obj_t * ui_BtnCamera7 = NULL;
lv_obj_t * ui_LblCamera7 = NULL;
lv_obj_t * ui_BtnSettingsOkSel = NULL;
lv_obj_t * ui_LblSettingsOk1 = NULL;
lv_obj_t * ui_BtnSettingsCancelSel = NULL;
lv_obj_t * ui_LblSettingsCancel1 = NULL;
// event funtions

// build funtions

void ui_CameraSelect_screen_init(void)
{
    ui_CameraSelect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CameraSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CameraSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CameraSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera0 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera0, 155);
    lv_obj_set_height(ui_BtnCamera0, 40);
    lv_obj_set_x(ui_BtnCamera0, -80);
    lv_obj_set_y(ui_BtnCamera0, -97);
    lv_obj_set_align(ui_BtnCamera0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera0 = lv_label_create(ui_BtnCamera0);
    lv_obj_set_width(ui_LblCamera0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera0, "Camera 0");
    lv_obj_set_style_text_color(ui_LblCamera0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera1 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera1, 155);
    lv_obj_set_height(ui_BtnCamera1, 40);
    lv_obj_set_x(ui_BtnCamera1, 79);
    lv_obj_set_y(ui_BtnCamera1, -97);
    lv_obj_set_align(ui_BtnCamera1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera1 = lv_label_create(ui_BtnCamera1);
    lv_obj_set_width(ui_LblCamera1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera1, "Camera 1");
    lv_obj_set_style_text_color(ui_LblCamera1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera2 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera2, 155);
    lv_obj_set_height(ui_BtnCamera2, 40);
    lv_obj_set_x(ui_BtnCamera2, -80);
    lv_obj_set_y(ui_BtnCamera2, -52);
    lv_obj_set_align(ui_BtnCamera2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera2 = lv_label_create(ui_BtnCamera2);
    lv_obj_set_width(ui_LblCamera2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera2, "Camera 2");
    lv_obj_set_style_text_color(ui_LblCamera2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera3 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera3, 155);
    lv_obj_set_height(ui_BtnCamera3, 40);
    lv_obj_set_x(ui_BtnCamera3, 79);
    lv_obj_set_y(ui_BtnCamera3, -52);
    lv_obj_set_align(ui_BtnCamera3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera3 = lv_label_create(ui_BtnCamera3);
    lv_obj_set_width(ui_LblCamera3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera3, "Camera 3");
    lv_obj_set_style_text_color(ui_LblCamera3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera4 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera4, 155);
    lv_obj_set_height(ui_BtnCamera4, 40);
    lv_obj_set_x(ui_BtnCamera4, -80);
    lv_obj_set_y(ui_BtnCamera4, -7);
    lv_obj_set_align(ui_BtnCamera4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera4 = lv_label_create(ui_BtnCamera4);
    lv_obj_set_width(ui_LblCamera4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera4, "Camera 4");
    lv_obj_set_style_text_color(ui_LblCamera4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera5 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera5, 155);
    lv_obj_set_height(ui_BtnCamera5, 40);
    lv_obj_set_x(ui_BtnCamera5, 79);
    lv_obj_set_y(ui_BtnCamera5, -7);
    lv_obj_set_align(ui_BtnCamera5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera5 = lv_label_create(ui_BtnCamera5);
    lv_obj_set_width(ui_LblCamera5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera5, "Camera 5");
    lv_obj_set_style_text_color(ui_LblCamera5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera6 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera6, 155);
    lv_obj_set_height(ui_BtnCamera6, 40);
    lv_obj_set_x(ui_BtnCamera6, -80);
    lv_obj_set_y(ui_BtnCamera6, 39);
    lv_obj_set_align(ui_BtnCamera6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera6 = lv_label_create(ui_BtnCamera6);
    lv_obj_set_width(ui_LblCamera6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera6, "Camera 6");
    lv_obj_set_style_text_color(ui_LblCamera6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCamera7 = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnCamera7, 155);
    lv_obj_set_height(ui_BtnCamera7, 40);
    lv_obj_set_x(ui_BtnCamera7, 79);
    lv_obj_set_y(ui_BtnCamera7, 39);
    lv_obj_set_align(ui_BtnCamera7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCamera7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCamera7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCamera7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCamera7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCamera7 = lv_label_create(ui_BtnCamera7);
    lv_obj_set_width(ui_LblCamera7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCamera7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCamera7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCamera7, "Camera 7");
    lv_obj_set_style_text_color(ui_LblCamera7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCamera7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSettingsOkSel = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnSettingsOkSel, 75);
    lv_obj_set_height(ui_BtnSettingsOkSel, 40);
    lv_obj_set_x(ui_BtnSettingsOkSel, 119);
    lv_obj_set_y(ui_BtnSettingsOkSel, 96);
    lv_obj_set_align(ui_BtnSettingsOkSel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSettingsOkSel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSettingsOkSel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSettingsOkSel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettingsOkSel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSettingsOk1 = lv_label_create(ui_BtnSettingsOkSel);
    lv_obj_set_width(ui_LblSettingsOk1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSettingsOk1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblSettingsOk1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSettingsOk1, "");
    lv_obj_set_style_text_color(ui_LblSettingsOk1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSettingsOk1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSettingsOk1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSettingsCancelSel = lv_btn_create(ui_CameraSelect);
    lv_obj_set_width(ui_BtnSettingsCancelSel, 75);
    lv_obj_set_height(ui_BtnSettingsCancelSel, 40);
    lv_obj_set_x(ui_BtnSettingsCancelSel, -120);
    lv_obj_set_y(ui_BtnSettingsCancelSel, 96);
    lv_obj_set_align(ui_BtnSettingsCancelSel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSettingsCancelSel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSettingsCancelSel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSettingsCancelSel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettingsCancelSel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSettingsCancel1 = lv_label_create(ui_BtnSettingsCancelSel);
    lv_obj_set_width(ui_LblSettingsCancel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSettingsCancel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblSettingsCancel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSettingsCancel1, "X");
    lv_obj_set_style_text_color(ui_LblSettingsCancel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSettingsCancel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSettingsCancel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_CameraSelect_screen_destroy(void)
{
    if(ui_CameraSelect) lv_obj_del(ui_CameraSelect);

    // NULL screen variables
    ui_CameraSelect = NULL;
    ui_BtnCamera0 = NULL;
    ui_LblCamera0 = NULL;
    ui_BtnCamera1 = NULL;
    ui_LblCamera1 = NULL;
    ui_BtnCamera2 = NULL;
    ui_LblCamera2 = NULL;
    ui_BtnCamera3 = NULL;
    ui_LblCamera3 = NULL;
    ui_BtnCamera4 = NULL;
    ui_LblCamera4 = NULL;
    ui_BtnCamera5 = NULL;
    ui_LblCamera5 = NULL;
    ui_BtnCamera6 = NULL;
    ui_LblCamera6 = NULL;
    ui_BtnCamera7 = NULL;
    ui_LblCamera7 = NULL;
    ui_BtnSettingsOkSel = NULL;
    ui_LblSettingsOk1 = NULL;
    ui_BtnSettingsCancelSel = NULL;
    ui_LblSettingsCancel1 = NULL;

}
