// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#include "../ui.h"

lv_obj_t * ui_Error = NULL;
lv_obj_t * ui_PnlError = NULL;
lv_obj_t * ui_LblErrorText = NULL;
lv_obj_t * ui_BtnErrorOk = NULL;
lv_obj_t * ui_LblErrorOk = NULL;
// event funtions

// build funtions

void ui_Error_screen_init(void)
{
    ui_Error = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Error, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Error, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Error, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlError = lv_obj_create(ui_Error);
    lv_obj_set_width(ui_PnlError, 314);
    lv_obj_set_height(ui_PnlError, 100);
    lv_obj_set_x(ui_PnlError, 0);
    lv_obj_set_y(ui_PnlError, -20);
    lv_obj_set_align(ui_PnlError, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlError, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PnlError, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlError, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblErrorText = lv_label_create(ui_PnlError);
    lv_obj_set_width(ui_LblErrorText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblErrorText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblErrorText, LV_ALIGN_CENTER);

    ui_BtnErrorOk = lv_btn_create(ui_Error);
    lv_obj_set_width(ui_BtnErrorOk, 75);
    lv_obj_set_height(ui_BtnErrorOk, 40);
    lv_obj_set_x(ui_BtnErrorOk, 119);
    lv_obj_set_y(ui_BtnErrorOk, 96);
    lv_obj_set_align(ui_BtnErrorOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnErrorOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnErrorOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnErrorOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnErrorOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblErrorOk = lv_label_create(ui_BtnErrorOk);
    lv_obj_set_width(ui_LblErrorOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblErrorOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblErrorOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblErrorOk, "");
    lv_obj_set_style_text_color(ui_LblErrorOk, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblErrorOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblErrorOk, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Error_screen_destroy(void)
{
    if(ui_Error) lv_obj_del(ui_Error);

    // NULL screen variables
    ui_Error = NULL;
    ui_PnlError = NULL;
    ui_LblErrorText = NULL;
    ui_BtnErrorOk = NULL;
    ui_LblErrorOk = NULL;

}
