// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#ifndef UI_ERROR_H
#define UI_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Error
extern void ui_Error_screen_init(void);
extern void ui_Error_screen_destroy(void);
extern lv_obj_t * ui_Error;
extern lv_obj_t * ui_PnlError;
extern lv_obj_t * ui_LblErrorText;
extern lv_obj_t * ui_BtnErrorOk;
extern lv_obj_t * ui_LblErrorOk;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

