// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#include "../ui.h"

lv_obj_t * ui_Loading = NULL;
lv_obj_t * ui_SpinnerLoading = NULL;
lv_obj_t * ui_LblLoading = NULL;
// event funtions

// build funtions

void ui_Loading_screen_init(void)
{
    ui_Loading = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Loading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerLoading = lv_spinner_create(ui_Loading, 1000, 90);
    lv_obj_set_width(ui_SpinnerLoading, 80);
    lv_obj_set_height(ui_SpinnerLoading, 80);
    lv_obj_set_x(ui_SpinnerLoading, 0);
    lv_obj_set_y(ui_SpinnerLoading, -27);
    lv_obj_set_align(ui_SpinnerLoading, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerLoading, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_SpinnerLoading, lv_color_hex(0x636363), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerLoading, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LblLoading = lv_label_create(ui_Loading);
    lv_obj_set_width(ui_LblLoading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblLoading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblLoading, 0);
    lv_obj_set_y(ui_LblLoading, 28);
    lv_obj_set_align(ui_LblLoading, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_LblLoading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Loading_screen_destroy(void)
{
    if(ui_Loading) lv_obj_del(ui_Loading);

    // NULL screen variables
    ui_Loading = NULL;
    ui_SpinnerLoading = NULL;
    ui_LblLoading = NULL;

}
