// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#ifndef UI_LOADING_H
#define UI_LOADING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Loading
extern void ui_Loading_screen_init(void);
extern void ui_Loading_screen_destroy(void);
extern lv_obj_t * ui_Loading;
extern lv_obj_t * ui_SpinnerLoading;
extern lv_obj_t * ui_LblLoading;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

