// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#ifndef UI_PINENTRY_H
#define UI_PINENTRY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PinEntry
extern void ui_PinEntry_screen_init(void);
extern void ui_PinEntry_screen_destroy(void);
extern lv_obj_t * ui_PinEntry;
extern lv_obj_t * ui_PnlInfo;
extern lv_obj_t * ui_LblKeyPadPrompt;
extern lv_obj_t * ui_BtnKeyPad0;
extern lv_obj_t * ui_LblKeyPad0;
extern lv_obj_t * ui_BtnKeyPad1;
extern lv_obj_t * ui_LblKeyPad1;
extern lv_obj_t * ui_BtnKeyPad2;
extern lv_obj_t * ui_LblKeyPad2;
extern lv_obj_t * ui_BtnKeyPad3;
extern lv_obj_t * ui_LblKeyPad3;
extern lv_obj_t * ui_BtnKeyPad4;
extern lv_obj_t * ui_LblKeyPad4;
extern lv_obj_t * ui_BtnKeyPad5;
extern lv_obj_t * ui_LblKeyPad5;
extern lv_obj_t * ui_BtnKeyPad6;
extern lv_obj_t * ui_LblKeyPad6;
extern lv_obj_t * ui_BtnKeyPad7;
extern lv_obj_t * ui_LblKeyPad7;
extern lv_obj_t * ui_BtnKeyPad8;
extern lv_obj_t * ui_LblKeyPad8;
extern lv_obj_t * ui_BtnKeyPad9;
extern lv_obj_t * ui_LblKeyPad9;
extern lv_obj_t * ui_BtnKeyPadA;
extern lv_obj_t * ui_LblKeyPadA;
extern lv_obj_t * ui_BtnKeyPadB;
extern lv_obj_t * ui_LblKeyPadB;
extern lv_obj_t * ui_BtnKeyPadC;
extern lv_obj_t * ui_LblKeyPadC;
extern lv_obj_t * ui_BtnKeyPadD;
extern lv_obj_t * ui_LblKeyPadD;
extern lv_obj_t * ui_BtnKeyPadOk;
extern lv_obj_t * ui_LblKeyPadOk;
extern lv_obj_t * ui_BtnKeyPadCancel;
extern lv_obj_t * ui_LblKeyPadCancel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BtnKeyPadB;
extern lv_obj_t * uic_BtnKeyPadC;
extern lv_obj_t * uic_BtnKeyPadD;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

