// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#include "../ui.h"

lv_obj_t * uic_BtnKeyPadD;
lv_obj_t * uic_BtnKeyPadC;
lv_obj_t * uic_BtnKeyPadB;
lv_obj_t * ui_PinEntry = NULL;
lv_obj_t * ui_PnlInfo = NULL;
lv_obj_t * ui_LblKeyPadPrompt = NULL;
lv_obj_t * ui_BtnKeyPad0 = NULL;
lv_obj_t * ui_LblKeyPad0 = NULL;
lv_obj_t * ui_BtnKeyPad1 = NULL;
lv_obj_t * ui_LblKeyPad1 = NULL;
lv_obj_t * ui_BtnKeyPad2 = NULL;
lv_obj_t * ui_LblKeyPad2 = NULL;
lv_obj_t * ui_BtnKeyPad3 = NULL;
lv_obj_t * ui_LblKeyPad3 = NULL;
lv_obj_t * ui_BtnKeyPad4 = NULL;
lv_obj_t * ui_LblKeyPad4 = NULL;
lv_obj_t * ui_BtnKeyPad5 = NULL;
lv_obj_t * ui_LblKeyPad5 = NULL;
lv_obj_t * ui_BtnKeyPad6 = NULL;
lv_obj_t * ui_LblKeyPad6 = NULL;
lv_obj_t * ui_BtnKeyPad7 = NULL;
lv_obj_t * ui_LblKeyPad7 = NULL;
lv_obj_t * ui_BtnKeyPad8 = NULL;
lv_obj_t * ui_LblKeyPad8 = NULL;
lv_obj_t * ui_BtnKeyPad9 = NULL;
lv_obj_t * ui_LblKeyPad9 = NULL;
lv_obj_t * ui_BtnKeyPadA = NULL;
lv_obj_t * ui_LblKeyPadA = NULL;
lv_obj_t * ui_BtnKeyPadB = NULL;
lv_obj_t * ui_LblKeyPadB = NULL;
lv_obj_t * ui_BtnKeyPadC = NULL;
lv_obj_t * ui_LblKeyPadC = NULL;
lv_obj_t * ui_BtnKeyPadD = NULL;
lv_obj_t * ui_LblKeyPadD = NULL;
lv_obj_t * ui_BtnKeyPadOk = NULL;
lv_obj_t * ui_LblKeyPadOk = NULL;
lv_obj_t * ui_BtnKeyPadCancel = NULL;
lv_obj_t * ui_LblKeyPadCancel = NULL;
// event funtions

// build funtions

void ui_PinEntry_screen_init(void)
{
    ui_PinEntry = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PinEntry, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PinEntry, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PinEntry, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlInfo = lv_obj_create(ui_PinEntry);
    lv_obj_set_width(ui_PnlInfo, 314);
    lv_obj_set_height(ui_PnlInfo, 30);
    lv_obj_set_x(ui_PnlInfo, 0);
    lv_obj_set_y(ui_PnlInfo, -102);
    lv_obj_set_align(ui_PnlInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblKeyPadPrompt = lv_label_create(ui_PnlInfo);
    lv_obj_set_width(ui_LblKeyPadPrompt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPadPrompt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPadPrompt, LV_ALIGN_CENTER);

    ui_BtnKeyPad0 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad0, 75);
    lv_obj_set_height(ui_BtnKeyPad0, 40);
    lv_obj_set_x(ui_BtnKeyPad0, 37);
    lv_obj_set_y(ui_BtnKeyPad0, 96);
    lv_obj_set_align(ui_BtnKeyPad0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad0 = lv_label_create(ui_BtnKeyPad0);
    lv_obj_set_width(ui_LblKeyPad0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad0, "0");
    lv_obj_set_style_text_color(ui_LblKeyPad0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad1 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad1, 75);
    lv_obj_set_height(ui_BtnKeyPad1, 40);
    lv_obj_set_x(ui_BtnKeyPad1, -46);
    lv_obj_set_y(ui_BtnKeyPad1, -63);
    lv_obj_set_align(ui_BtnKeyPad1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad1 = lv_label_create(ui_BtnKeyPad1);
    lv_obj_set_width(ui_LblKeyPad1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad1, "1");
    lv_obj_set_style_text_color(ui_LblKeyPad1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad2 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad2, 75);
    lv_obj_set_height(ui_BtnKeyPad2, 40);
    lv_obj_set_x(ui_BtnKeyPad2, 37);
    lv_obj_set_y(ui_BtnKeyPad2, -63);
    lv_obj_set_align(ui_BtnKeyPad2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad2 = lv_label_create(ui_BtnKeyPad2);
    lv_obj_set_width(ui_LblKeyPad2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad2, "2");
    lv_obj_set_style_text_color(ui_LblKeyPad2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad3 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad3, 75);
    lv_obj_set_height(ui_BtnKeyPad3, 40);
    lv_obj_set_x(ui_BtnKeyPad3, 119);
    lv_obj_set_y(ui_BtnKeyPad3, -63);
    lv_obj_set_align(ui_BtnKeyPad3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad3 = lv_label_create(ui_BtnKeyPad3);
    lv_obj_set_width(ui_LblKeyPad3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad3, "3");
    lv_obj_set_style_text_color(ui_LblKeyPad3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad4 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad4, 75);
    lv_obj_set_height(ui_BtnKeyPad4, 40);
    lv_obj_set_x(ui_BtnKeyPad4, -46);
    lv_obj_set_y(ui_BtnKeyPad4, -10);
    lv_obj_set_align(ui_BtnKeyPad4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad4 = lv_label_create(ui_BtnKeyPad4);
    lv_obj_set_width(ui_LblKeyPad4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad4, "4");
    lv_obj_set_style_text_color(ui_LblKeyPad4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad5 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad5, 75);
    lv_obj_set_height(ui_BtnKeyPad5, 40);
    lv_obj_set_x(ui_BtnKeyPad5, 37);
    lv_obj_set_y(ui_BtnKeyPad5, -10);
    lv_obj_set_align(ui_BtnKeyPad5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad5 = lv_label_create(ui_BtnKeyPad5);
    lv_obj_set_width(ui_LblKeyPad5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad5, "5");
    lv_obj_set_style_text_color(ui_LblKeyPad5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad6 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad6, 75);
    lv_obj_set_height(ui_BtnKeyPad6, 40);
    lv_obj_set_x(ui_BtnKeyPad6, 119);
    lv_obj_set_y(ui_BtnKeyPad6, -10);
    lv_obj_set_align(ui_BtnKeyPad6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad6 = lv_label_create(ui_BtnKeyPad6);
    lv_obj_set_width(ui_LblKeyPad6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad6, "6");
    lv_obj_set_style_text_color(ui_LblKeyPad6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad7 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad7, 75);
    lv_obj_set_height(ui_BtnKeyPad7, 40);
    lv_obj_set_x(ui_BtnKeyPad7, -46);
    lv_obj_set_y(ui_BtnKeyPad7, 43);
    lv_obj_set_align(ui_BtnKeyPad7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad7 = lv_label_create(ui_BtnKeyPad7);
    lv_obj_set_width(ui_LblKeyPad7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad7, "7");
    lv_obj_set_style_text_color(ui_LblKeyPad7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad8 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad8, 75);
    lv_obj_set_height(ui_BtnKeyPad8, 40);
    lv_obj_set_x(ui_BtnKeyPad8, 37);
    lv_obj_set_y(ui_BtnKeyPad8, 43);
    lv_obj_set_align(ui_BtnKeyPad8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad8 = lv_label_create(ui_BtnKeyPad8);
    lv_obj_set_width(ui_LblKeyPad8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad8, "8");
    lv_obj_set_style_text_color(ui_LblKeyPad8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPad9 = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPad9, 75);
    lv_obj_set_height(ui_BtnKeyPad9, 40);
    lv_obj_set_x(ui_BtnKeyPad9, 119);
    lv_obj_set_y(ui_BtnKeyPad9, 43);
    lv_obj_set_align(ui_BtnKeyPad9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPad9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPad9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPad9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPad9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPad9 = lv_label_create(ui_BtnKeyPad9);
    lv_obj_set_width(ui_LblKeyPad9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPad9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPad9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPad9, "9");
    lv_obj_set_style_text_color(ui_LblKeyPad9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPad9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPadA = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPadA, 50);
    lv_obj_set_height(ui_BtnKeyPadA, 40);
    lv_obj_set_x(ui_BtnKeyPadA, -132);
    lv_obj_set_y(ui_BtnKeyPadA, -63);
    lv_obj_set_align(ui_BtnKeyPadA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPadA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPadA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPadA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPadA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPadA = lv_label_create(ui_BtnKeyPadA);
    lv_obj_set_width(ui_LblKeyPadA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPadA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPadA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPadA, "A");
    lv_obj_set_style_text_color(ui_LblKeyPadA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPadA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPadB = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPadB, 50);
    lv_obj_set_height(ui_BtnKeyPadB, 40);
    lv_obj_set_x(ui_BtnKeyPadB, -132);
    lv_obj_set_y(ui_BtnKeyPadB, -10);
    lv_obj_set_align(ui_BtnKeyPadB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPadB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPadB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPadB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPadB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPadB = lv_label_create(ui_BtnKeyPadB);
    lv_obj_set_width(ui_LblKeyPadB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPadB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPadB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPadB, "B");
    lv_obj_set_style_text_color(ui_LblKeyPadB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPadB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPadC = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPadC, 50);
    lv_obj_set_height(ui_BtnKeyPadC, 40);
    lv_obj_set_x(ui_BtnKeyPadC, -132);
    lv_obj_set_y(ui_BtnKeyPadC, 43);
    lv_obj_set_align(ui_BtnKeyPadC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPadC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPadC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPadC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPadC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPadC = lv_label_create(ui_BtnKeyPadC);
    lv_obj_set_width(ui_LblKeyPadC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPadC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPadC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPadC, "C");
    lv_obj_set_style_text_color(ui_LblKeyPadC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPadC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPadD = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPadD, 50);
    lv_obj_set_height(ui_BtnKeyPadD, 40);
    lv_obj_set_x(ui_BtnKeyPadD, -132);
    lv_obj_set_y(ui_BtnKeyPadD, 96);
    lv_obj_set_align(ui_BtnKeyPadD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPadD, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPadD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPadD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPadD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPadD = lv_label_create(ui_BtnKeyPadD);
    lv_obj_set_width(ui_LblKeyPadD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPadD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPadD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPadD, "D");
    lv_obj_set_style_text_color(ui_LblKeyPadD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPadD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPadOk = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPadOk, 75);
    lv_obj_set_height(ui_BtnKeyPadOk, 40);
    lv_obj_set_x(ui_BtnKeyPadOk, 119);
    lv_obj_set_y(ui_BtnKeyPadOk, 96);
    lv_obj_set_align(ui_BtnKeyPadOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPadOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPadOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPadOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPadOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPadOk = lv_label_create(ui_BtnKeyPadOk);
    lv_obj_set_width(ui_LblKeyPadOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPadOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPadOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPadOk, "");
    lv_obj_set_style_text_color(ui_LblKeyPadOk, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPadOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblKeyPadOk, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnKeyPadCancel = lv_btn_create(ui_PinEntry);
    lv_obj_set_width(ui_BtnKeyPadCancel, 75);
    lv_obj_set_height(ui_BtnKeyPadCancel, 40);
    lv_obj_set_x(ui_BtnKeyPadCancel, -46);
    lv_obj_set_y(ui_BtnKeyPadCancel, 96);
    lv_obj_set_align(ui_BtnKeyPadCancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnKeyPadCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnKeyPadCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnKeyPadCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnKeyPadCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblKeyPadCancel = lv_label_create(ui_BtnKeyPadCancel);
    lv_obj_set_width(ui_LblKeyPadCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyPadCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyPadCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblKeyPadCancel, "X");
    lv_obj_set_style_text_color(ui_LblKeyPadCancel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblKeyPadCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblKeyPadCancel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_BtnKeyPadB = ui_BtnKeyPadB;
    uic_BtnKeyPadC = ui_BtnKeyPadC;
    uic_BtnKeyPadD = ui_BtnKeyPadD;

}

void ui_PinEntry_screen_destroy(void)
{
    if(ui_PinEntry) lv_obj_del(ui_PinEntry);

    // NULL screen variables
    ui_PinEntry = NULL;
    ui_PnlInfo = NULL;
    ui_LblKeyPadPrompt = NULL;
    ui_BtnKeyPad0 = NULL;
    ui_LblKeyPad0 = NULL;
    ui_BtnKeyPad1 = NULL;
    ui_LblKeyPad1 = NULL;
    ui_BtnKeyPad2 = NULL;
    ui_LblKeyPad2 = NULL;
    ui_BtnKeyPad3 = NULL;
    ui_LblKeyPad3 = NULL;
    ui_BtnKeyPad4 = NULL;
    ui_LblKeyPad4 = NULL;
    ui_BtnKeyPad5 = NULL;
    ui_LblKeyPad5 = NULL;
    ui_BtnKeyPad6 = NULL;
    ui_LblKeyPad6 = NULL;
    ui_BtnKeyPad7 = NULL;
    ui_LblKeyPad7 = NULL;
    ui_BtnKeyPad8 = NULL;
    ui_LblKeyPad8 = NULL;
    ui_BtnKeyPad9 = NULL;
    ui_LblKeyPad9 = NULL;
    ui_BtnKeyPadA = NULL;
    ui_LblKeyPadA = NULL;
    uic_BtnKeyPadB = NULL;
    ui_BtnKeyPadB = NULL;
    ui_LblKeyPadB = NULL;
    uic_BtnKeyPadC = NULL;
    ui_BtnKeyPadC = NULL;
    ui_LblKeyPadC = NULL;
    uic_BtnKeyPadD = NULL;
    ui_BtnKeyPadD = NULL;
    ui_LblKeyPadD = NULL;
    ui_BtnKeyPadOk = NULL;
    ui_LblKeyPadOk = NULL;
    ui_BtnKeyPadCancel = NULL;
    ui_LblKeyPadCancel = NULL;

}
