// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#include "../ui.h"

lv_obj_t * uic_BtnSettingsPlaceholder;
lv_obj_t * ui_SettingsLanding = NULL;
lv_obj_t * ui_BtnChangePin = NULL;
lv_obj_t * ui_LblChangePin = NULL;
lv_obj_t * ui_BtnModifyFull = NULL;
lv_obj_t * ui_LblChangeFullScene = NULL;
lv_obj_t * ui_BtnModifyPartial = NULL;
lv_obj_t * ui_LblModifyPartial = NULL;
lv_obj_t * ui_BtnModifyDisarmed = NULL;
lv_obj_t * ui_LblModifyDisarmed = NULL;
lv_obj_t * ui_BtnSettingsOkSet = NULL;
lv_obj_t * ui_LblSettingsOk3 = NULL;
lv_obj_t * ui_BtnSettingsCancelSet = NULL;
lv_obj_t * ui_LblSettingsCancel3 = NULL;
// event funtions

// build funtions

void ui_SettingsLanding_screen_init(void)
{
    ui_SettingsLanding = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsLanding, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsLanding, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsLanding, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnChangePin = lv_btn_create(ui_SettingsLanding);
    lv_obj_set_width(ui_BtnChangePin, 314);
    lv_obj_set_height(ui_BtnChangePin, 40);
    lv_obj_set_x(ui_BtnChangePin, 0);
    lv_obj_set_y(ui_BtnChangePin, -97);
    lv_obj_set_align(ui_BtnChangePin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnChangePin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnChangePin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnChangePin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnChangePin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblChangePin = lv_label_create(ui_BtnChangePin);
    lv_obj_set_width(ui_LblChangePin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblChangePin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblChangePin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblChangePin, "Change Pin Code");
    lv_obj_set_style_text_color(ui_LblChangePin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblChangePin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnModifyFull = lv_btn_create(ui_SettingsLanding);
    lv_obj_set_width(ui_BtnModifyFull, 314);
    lv_obj_set_height(ui_BtnModifyFull, 40);
    lv_obj_set_x(ui_BtnModifyFull, 0);
    lv_obj_set_y(ui_BtnModifyFull, -52);
    lv_obj_set_align(ui_BtnModifyFull, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnModifyFull, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnModifyFull, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnModifyFull, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnModifyFull, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblChangeFullScene = lv_label_create(ui_BtnModifyFull);
    lv_obj_set_width(ui_LblChangeFullScene, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblChangeFullScene, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblChangeFullScene, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblChangeFullScene, "Modify Full Alarm");
    lv_obj_set_style_text_color(ui_LblChangeFullScene, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblChangeFullScene, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnModifyPartial = lv_btn_create(ui_SettingsLanding);
    lv_obj_set_width(ui_BtnModifyPartial, 314);
    lv_obj_set_height(ui_BtnModifyPartial, 40);
    lv_obj_set_x(ui_BtnModifyPartial, 0);
    lv_obj_set_y(ui_BtnModifyPartial, -7);
    lv_obj_set_align(ui_BtnModifyPartial, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnModifyPartial, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnModifyPartial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnModifyPartial, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnModifyPartial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblModifyPartial = lv_label_create(ui_BtnModifyPartial);
    lv_obj_set_width(ui_LblModifyPartial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblModifyPartial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblModifyPartial, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblModifyPartial, "Modify Partial Alarm");
    lv_obj_set_style_text_color(ui_LblModifyPartial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblModifyPartial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnModifyDisarmed = lv_btn_create(ui_SettingsLanding);
    lv_obj_set_width(ui_BtnModifyDisarmed, 314);
    lv_obj_set_height(ui_BtnModifyDisarmed, 40);
    lv_obj_set_x(ui_BtnModifyDisarmed, 0);
    lv_obj_set_y(ui_BtnModifyDisarmed, 39);
    lv_obj_set_align(ui_BtnModifyDisarmed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnModifyDisarmed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnModifyDisarmed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnModifyDisarmed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnModifyDisarmed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblModifyDisarmed = lv_label_create(ui_BtnModifyDisarmed);
    lv_obj_set_width(ui_LblModifyDisarmed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblModifyDisarmed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblModifyDisarmed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblModifyDisarmed, "Modify Disarmed");
    lv_obj_set_style_text_color(ui_LblModifyDisarmed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblModifyDisarmed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSettingsOkSet = lv_btn_create(ui_SettingsLanding);
    lv_obj_set_width(ui_BtnSettingsOkSet, 75);
    lv_obj_set_height(ui_BtnSettingsOkSet, 40);
    lv_obj_set_x(ui_BtnSettingsOkSet, 119);
    lv_obj_set_y(ui_BtnSettingsOkSet, 96);
    lv_obj_set_align(ui_BtnSettingsOkSet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSettingsOkSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSettingsOkSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSettingsOkSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettingsOkSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSettingsOk3 = lv_label_create(ui_BtnSettingsOkSet);
    lv_obj_set_width(ui_LblSettingsOk3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSettingsOk3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblSettingsOk3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSettingsOk3, "");
    lv_obj_set_style_text_color(ui_LblSettingsOk3, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSettingsOk3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSettingsOk3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSettingsCancelSet = lv_btn_create(ui_SettingsLanding);
    lv_obj_set_width(ui_BtnSettingsCancelSet, 75);
    lv_obj_set_height(ui_BtnSettingsCancelSet, 40);
    lv_obj_set_x(ui_BtnSettingsCancelSet, -120);
    lv_obj_set_y(ui_BtnSettingsCancelSet, 96);
    lv_obj_set_align(ui_BtnSettingsCancelSet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSettingsCancelSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSettingsCancelSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSettingsCancelSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettingsCancelSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSettingsCancel3 = lv_label_create(ui_BtnSettingsCancelSet);
    lv_obj_set_width(ui_LblSettingsCancel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSettingsCancel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblSettingsCancel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSettingsCancel3, "X");
    lv_obj_set_style_text_color(ui_LblSettingsCancel3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSettingsCancel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSettingsCancel3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_BtnSettingsPlaceholder = ui_BtnModifyDisarmed;

}

void ui_SettingsLanding_screen_destroy(void)
{
    if(ui_SettingsLanding) lv_obj_del(ui_SettingsLanding);

    // NULL screen variables
    ui_SettingsLanding = NULL;
    ui_BtnChangePin = NULL;
    ui_LblChangePin = NULL;
    ui_BtnModifyFull = NULL;
    ui_LblChangeFullScene = NULL;
    ui_BtnModifyPartial = NULL;
    ui_LblModifyPartial = NULL;
    uic_BtnSettingsPlaceholder = NULL;
    ui_BtnModifyDisarmed = NULL;
    ui_LblModifyDisarmed = NULL;
    ui_BtnSettingsOkSet = NULL;
    ui_LblSettingsOk3 = NULL;
    ui_BtnSettingsCancelSet = NULL;
    ui_LblSettingsCancel3 = NULL;

}
