// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ReoAlarmUI

#ifndef UI_SETTINGSLANDING_H
#define UI_SETTINGSLANDING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsLanding
extern void ui_SettingsLanding_screen_init(void);
extern void ui_SettingsLanding_screen_destroy(void);
extern lv_obj_t * ui_SettingsLanding;
extern lv_obj_t * ui_BtnChangePin;
extern lv_obj_t * ui_LblChangePin;
extern lv_obj_t * ui_BtnModifyFull;
extern lv_obj_t * ui_LblChangeFullScene;
extern lv_obj_t * ui_BtnModifyPartial;
extern lv_obj_t * ui_LblModifyPartial;
extern lv_obj_t * ui_BtnModifyDisarmed;
extern lv_obj_t * ui_LblModifyDisarmed;
extern lv_obj_t * ui_BtnSettingsOkSet;
extern lv_obj_t * ui_LblSettingsOk3;
extern lv_obj_t * ui_BtnSettingsCancelSet;
extern lv_obj_t * ui_LblSettingsCancel3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BtnSettingsPlaceholder;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

